### ISSUE TITLE
Refactor registration flow for multi-cluster

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#162]
1. Registration app calls Auth service whenever a new user is approved, instead of calling keycloak.
2. Auth services persists the user information which includes **cluster info** and **approved=true**
3. Expose this info to other services in OpenShift.io / fabric8.

Tasks:

- [x]  Make data model changes for storing cluster information. https://github.com/fabric8-services/fabric8-auth/issues/165
- [x]  Add API for creating a user in AUTH - which would be used by the Registration App to 'inform' Auth about the new provisioned user. https://github.com/fabric8-services/fabric8-auth/issues/166
- [x] Add credentials for the registration app service account. https://github.com/fabric8-services/fabric8-auth/issues/171
- [x]  Workflow for Auth service to add provisioned user's info inside keycloak. https://github.com/fabric8-services/fabric8-auth/issues/167
- [x] Switch the registration app to the new Auth API to register a new provisioned user. https://github.com/openshift/online-registration/issues/762

**Comment by alexeykazakov** [comment]
Done
