### ISSUE TITLE
Initial version of Token Storage to cover existing GitHub/OSO token functionality

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#21]
As the first step we should provide our own implementation to cover all Keycloak functionality currently used by OSIO:

- [x] Add data model - #132
- [x] Account linking REST API - #134
- [x] OSO/GitHub token obtaining REST API (Check if token exists in KC. If not check local DB) - #133 
- [x] Update OSO clients. Configure configmaps/secrets in OSDs.
- [x] Switch OSIO clients to Auth instead of WIT/KC to obtain tokens - https://github.com/fabric8-services/fabric8-auth/issues/149
- [x] Switch UI to new API to link accounts and Update GitHub oauth2 apps - https://github.com/fabric8-services/fabric8-auth/issues/157
- [x] Get Token API: Check if token exists in the local DB first. If not check KC - https://github.com/fabric8-services/fabric8-auth/issues/156

## Rollout plan - 

- [x] Rollout the "GET" token API which would currently fetch the token stored in keycloak. ( and store in db for subsequent requests ) 
- [x] Rollout the new account linking API
- [x] Have all clients migrate to the new API for getting tokens.
- [x] Update linking URL in fabric8-ui Getting Started page & Update redirect URL in the GitHub oauth apps.
- [x] Get Token API: Check if token exists in the local DB first. If not check KC.

**Comment by alexeykazakov** [comment]
Done
