### ISSUE TITLE
Support private emails

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#241]
Private email are not visible to other users.
Users can make their emails private/public in the user profile page.

- [x] Support private emails in Auth back-end - https://github.com/fabric8-services/fabric8-auth/issues/35
- [x] Support email notifications for private emails - https://github.com/fabric8-services/fabric8-notification/issues/52
- [x] Add private/public email switch to user profile page - https://github.com/openshiftio/openshift.io/issues/1775

**Comment by alexeykazakov** [comment]
Done
