### ISSUE TITLE
Migrate existing authz to native authz

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#359]
The task where we can list all the sub-tasks with GH issue numbers that need to be completed to be able to replace the existing authz capabilities we have in the auth service, with the new native authz capabilities.

### Stage 1 

Needs to go in as a single PR - this does not remove keycloak authz, rather complements it because workitem crud controllers in WIT would still be using keycloak authz

- [x] Everytime a new space is created, create a new resource for the same. #366
- [x] Assign/Remove collaborator role when adding/removing space contributors #511 
- [x] Migrate existing space collaborators data ( DB migration ) #365
- [x] Collaborators API : Start using the authorization service, https://github.com/fabric8-services/fabric8-auth/issues/364

### Stage 2

- [x] Cutoff keycloak authz - https://github.com/fabric8-services/fabric8-auth/pull/533 https://github.com/fabric8-services/fabric8-auth/issues/539
- [x] WIT: Refactor Authz lookups during workitem operations to use new Authz API which checks if user has a specific scope - #493  

### Stage 3
- [ ] ~~Add support for storing authz info in the token. ( existing authz works without this )~~
- [ ] ~~On creation of areas/iterations , creating corresponding `resources` in the `resource` table.~~
- [ ] ~~Make existing areas/iterations 'authorization aware' ( DB migration )~~
