### ISSUE TITLE
Local development setup on minishift

### ISSUE THREAD

**Issue by dipak-pawar** [fabric8-services/fabric8-auth#551]
### Tasks
- [x] Currently, we have auth and other services running using `kedge`.  Migrate it to use openshift template.
- [x] Add make target to run `auth`, `wit`, `fabric8-ui` locally
- [x] Add documentation for above steps
- [x] Add make target to redeploy auth built from latest code.
