### ISSUE TITLE
Migrate space authorization from WIT to Auth

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#65]
- [x] Delegate Keycloak space resource creation from WIT to Auth - https://github.com/fabric8-services/fabric8-auth/issues/27
- [x] Copy already existing Space Resources entities from WIT DB to Auth - https://github.com/fabric8-services/fabric8-auth/issues/75
- [ ] ~~Switch UI from using WIT REST API to Auth REST API to manage collaborators~~ Moved to #127 
- [x] Drop Space Resources table and clean up all related code in WIT

**Comment by alexeykazakov** [comment]
Blocked by https://github.com/fabric8-services/fabric8-auth/issues/25

**Comment by alexeykazakov** [comment]
The UI part is moved to #127 
The rest is done.
