### ISSUE TITLE
[epic] Changes in user registration flow to support custom cluster selection

### ISSUE THREAD

**Issue by xcoulon** [fabric8-services/fabric8-auth#720]
the following changes need to be applied in `fabric8-auth` in order to use the new identity/cluster relationship endpoint in the cluster service (https://github.com/fabric8-services/fabric8-cluster/issues/15):

- [x] call the new identity/cluster relationship endpoint in cluster service during registration of user #744 
- [x] migration to create identity/cluster relationships in cluster service for existing user
- [ ] proxy list clusters for user from auth to cluster service

**Comment by dipak-pawar** [comment]
@xcoulon: Can you remind me what is need of proxy list clusters for a user from auth to cluster service if we can call directly to cluster?

**Comment by xcoulon** [comment]
> @xcoulon: Can you remind me what is need of proxy list clusters for a user from auth to cluster service if we can call directly to cluster?

I added this item in order to make sure that existing clients can still call the `auth` service, but their requests would be proxied to the `cluster` service. In the mean time, `auth` service wouldn't need to keep a copy of the cluster info, but this wouldn't break the platform.

**Comment by dipak-pawar** [comment]
I think it's already in place https://github.com/fabric8-services/fabric8-auth/blob/master/controller/clusters.go#L38. Or Are you expecting something else?

**Comment by xcoulon** [comment]
> @xcoulon I think it's already in place https://github.com/fabric8-services/fabric8-auth/blob/master/controller/clusters.go#L38. Or Are you expecting something else?

@dipak-pawar great! in that case, it's all good ;)

**Comment by dipak-pawar** [comment]
Closing this as everything is in place.
