### ISSUE TITLE
[Epic] User deactivation

### ISSUE THREAD

**Issue by xcoulon** [fabric8-services/fabric8-auth#774]
Provide a new `/api/namedusers/:username/deactivate` endpoint to:
- [x] https://github.com/fabric8-services/fabric8-auth/issues/775 obfuscate and deactivate the account in `auth` service
- [x] https://github.com/fabric8-services/fabric8-auth/issues/776 revoke all tokens
- [x] https://github.com/fabric8-services/fabric8-auth/issues/777 call other services to deactivate the account
- [x] https://github.com/fabric8-services/fabric8-auth/issues/778 soft-delete the account
- [x] https://github.com/fabric8-services/fabric8-auth/issues/783 unlink the external accounts (GitHub, etc.)
- [x] https://github.com/fabric8-services/fabric8-auth/issues/780 expose endpoint (once everything else above is done, since we don't want to expose an incomplete feature)
- [x] https://github.com/fabric8-services/fabric8-auth/issues/796 track user activity based on token validation and renewal
- [x] ~~https://github.com/fabric8-services/fabric8-auth/issues/791 expose endpoint to list the users to deactivate~~

**Comment by alexeykazakov** [comment]
> * unlink the external accounts? (GitHub, etc.)

Good point. Yes!

**Comment by xcoulon** [comment]
> > * unlink the external accounts? (GitHub, etc.)
> 
> Good point. Yes!

added in https://github.com/fabric8-services/fabric8-auth/issues/783

**Comment by alexeykazakov** [comment]
We also need to make sure that we log all deprovisioned users.

**Comment by alexeykazakov** [comment]
There is one subtask is missing. Before we expose the endpoint we have to change the registration endpoint. It should handle the situation when we get a request to register a new user who was previously deactivated/soft-deleted.

**Comment by alexeykazakov** [comment]
Never mind. With data obfuscation we don't have to do extra in the registration flow :)

**Comment by alexeykazakov** [comment]
This Epic (provide `/api/namedusers/:username/deactivate` endpoint) is done. Closing it.

**Comment by xcoulon** [comment]
reopening as I realized that https://github.com/fabric8-services/fabric8-auth/issues/777 was incomplete (missing calls to Che, Jenkins and Env services).
