### ISSUE TITLE
Migrate User/Identity management from WIT to Auth

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#79]
( Based on Aug 31st's discussion between @alexeykazakov and sbose )

**Phase 1** - continue using WIT , but add support in AUTH. :  https://github.com/fabric8-services/fabric8-auth/issues/26

- [x]  Add support in WIT for creating  user/identity through the UPDATE API. 
- [x]  **On successful login using Auth service,** If user is present in Auth DB, Add support in Auth Login workflow to call "update user api" of WIT, .
- [x] **On successful login using Auth service,** If user is NOT present in Auth DB,  Add support in Auth Login workflow to 'GET user profile info' from WIT.  After writing to AUTH DB, call "User update api" of WIT to sync the updated user profile info.
- [x] When user profile is updated in Auth call WIT to update the user in the WIT DB.

**Phase 2** - start using the Auth service :  https://github.com/fabric8-services/fabric8-auth/issues/26

- [x] 302 Redirect requests from WIT to AUTH for login, logout, account linking - https://github.com/fabric8-services/fabric8-wit/pull/1650
- [x] Delegate requests for token refresh from WIT to AUTH. ( Delegate instead of redirect, because here a payload needs to be forwarded too, which is easier when delegated instead of redirected. ) - https://github.com/fabric8-services/fabric8-wit/pull/1650
- [x] Delegate user profile update from WIT to AUTH - https://github.com/fabric8-services/fabric8-wit/pull/1650

**Phase 3** - Migrate data
- [x] Migrate user data from WIT db to AUTH db - this is a db admin task, https://github.com/fabric8-services/fabric8-auth/issues/25

~~**Phase 4** - Switch UI to AUTH~~
- [ ] ~~Switch UI (openshiftio app, fabric8-ui, planner) from WIT API to  Auth API for /login, /logout, /refresh, /linksession, /user, /users:id, /spaces/:spaceID/collaborators~~
Moved to https://github.com/fabric8-services/fabric8-auth/issues/127

**Phase 5** - Clean up WIT
- [x] Replace all call delegation in WIT by 302 redirects to AUTH (/users, /login/refresh) - https://github.com/fabric8-services/fabric8-wit/pull/1667
- [x] Clean up WIT code and DB schema to remove unused stuff - https://github.com/fabric8-services/fabric8-wit/pull/1667

**Comment by alexeykazakov** [comment]
Phase 1 should also include a step to support creating a new user in WIT when user is trying to login first time.

And there is also Phase 5 - clean WIT (remove unused code and keep only needed info in user/identity tables.

**Comment by sbose78** [comment]
UI changes : 
Noting down changes that need to be done for making UI using auth.openshift.io

- Update URL from `/api/login/authorize` to `/api/login`  https://github.com/fabric8-ui/fabric8-planner/blob/b07ab261735adf025fdb0273e17110ab825c7c0e/src/app/services/login.service.ts#L17
- Update URL from `/api/login/authorize` to `/api/login`  https://github.com/fabric8-ui/fabric8-ui/blob/9980b179b432d16cf4a8e4b5c29a3702ab9fd33c/src/app/shared/login.service.ts#L42
- Use 'AUTH_API_URL' instead of 'WIT_API_URL' https://github.com/fabric8-ui/fabric8-ui/blob/9980b179b432d16cf4a8e4b5c29a3702ab9fd33c/src/app/shared/login.service.ts#L33
- Add the AUTH_API_URL in https://github.com/fabric8-ui/fabric8-ui/blob/master/config/webpack.prod.js ( and other webpack.*.js too )
- Add auth to https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/shared/api-locator.service.ts

**Comment by alexeykazakov** [comment]
> UI changes :

Good findings! Does these changes cover /login, /logout, /refresh ?
We will need to change /user, /users too but later.

**Comment by alexeykazakov** [comment]
UI part is moved to #127.
The rest is done.
